const CACHE='statforge-v1.2.0';
const ASSETS=["./", "./index.html", "./css/styles.css", "./js/data.js", "./js/storage.js", "./js/combat.js", "./js/app.js", "./manifest.webmanifest", "./assets/icons/icon-192.png", "./assets/icons/icon-512.png", "./assets/icons/logo.svg", "./vendor/zxing-library.min.js", "./vendor/zxing-browser.min.js", "./assets/exercises/pushup.svg", "./assets/exercises/plank.svg", "./assets/exercises/rower.svg", "./assets/exercises/chest_press.svg", "./assets/exercises/seated_row.svg", "./assets/exercises/lat_pulldown.svg", "./assets/exercises/leg_press.svg", "./assets/exercises/leg_curl.svg", "./assets/exercises/leg_extension.svg", "./assets/exercises/face_pull.svg", "./assets/exercises/shoulder_press.svg", "./assets/exercises/farmer_carry.svg", "./assets/exercises/step_up.svg", "./assets/exercises/calf_raise.svg", "./assets/exercises/pallof.svg", "./assets/exercises/side_plank.svg", "./assets/exercises/dead_bug.svg", "./assets/exercises/bird_dog.svg", "./assets/exercises/walk.svg", "./assets/exercises/chair_stand.svg", "./assets/exercises/wall_sit.svg", "./assets/exercises/balance.svg", "./assets/exercises/march.svg", "./assets/enemies/giant-rat.svg", "./assets/enemies/goblin-minion.svg", "./assets/enemies/wolf.svg", "./assets/enemies/skeleton.svg", "./assets/enemies/goblin-warrior.svg", "./assets/enemies/dire-wolf.svg", "./assets/enemies/goblin-boss.svg", "./assets/enemies/minotaur-skeleton.svg", "./assets/enemies/ogre.svg", "./assets/enemies/giant-scorpion.svg", "./assets/enemies/red-dragon-wyrmling.svg", "./assets/enemies/troll.svg", "./assets/enemies/young-red-dragon.svg"];
self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS)).then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',e=>{
 if(e.request.method!=='GET') return;
 const url=new URL(e.request.url);
 if(url.hostname.includes('openfoodfacts.org')){ e.respondWith(fetch(e.request).catch(()=>new Response(JSON.stringify({status:0}),{headers:{'Content-Type':'application/json'}}))); return; }
 e.respondWith(caches.match(e.request).then(r=>r||fetch(e.request).then(resp=>{const clone=resp.clone();caches.open(CACHE).then(c=>c.put(e.request,clone));return resp;}).catch(()=>caches.match('./index.html'))));
});