// Ascendry public alpha cache manifest — adaptive coaching 0.9.2
importScripts('./js/version.js');
const VERSION='0.9.2';
const CACHE=`ascendry-alpha-v${VERSION}`;
const v=`?v=${encodeURIComponent(VERSION)}`;
const ASSETS=['./','./index.html',`./index.html${v}`,`./css/styles.css${v}`,`./css/alpha.css${v}`,`./css/alpha-avatar-figure.css${v}`,`./css/alpha-game.css${v}`,`./css/alpha-game-avatar-slot.css${v}`,`./css/alpha-public-polish.css${v}`,`./css/alpha-coaching.css${v}`,`./css/alpha-quest-compact.css${v}`,`./css/alpha-workout.css${v}`,`./css/alpha-workout-fantasy.css${v}`,`./js/version.js${v}`,`./js/data.js${v}`,`./js/storage.js${v}`,`./js/alpha-lorelei-engine.js${v}`,`./js/alpha-avatar-palettes.js${v}`,`./js/alpha-avatar-config.js${v}`,`./js/alpha-accent.js${v}`,`./js/alpha-upgrade.js${v}`,`./js/alpha-life-quests.js${v}`,`./js/alpha-life-quest-engine.js${v}`,`./js/alpha-life-preview-guard.js${v}`,`./js/alpha-life-quest-content.js${v}`,`./js/alpha-coaching-model.js${v}`,`./js/alpha-coaching-stability.js${v}`,`./js/alpha.js${v}`,`./js/alpha-coaching-ui.js${v}`,`./js/alpha-avatar-canonical.js${v}`,`./js/alpha-game-avatar-slot.js${v}`,`./js/alpha-exercises.js${v}`,`./js/alpha-onboarding-tools.js${v}`,`./js/alpha-generator.js${v}`,`./js/alpha-workout-core.js${v}`,`./js/alpha-runner.js${v}`,`./js/alpha-workout-interactions.js${v}`,`./js/alpha-game-data.js${v}`,`./js/alpha-game-engine.js${v}`,`./js/alpha-game-class-options.js${v}`,`./js/alpha-game-ui.js${v}`,`./js/alpha-game-action-gestures.js${v}`,`./js/alpha-public-polish.js${v}`,'./manifest.webmanifest',`./manifest.webmanifest${v}`,'./assets/icons/icon-192.png','./assets/icons/icon-512.png','./assets/icons/logo.svg','./assets/exercises/pushup.svg','./assets/exercises/plank.svg','./assets/exercises/rower.svg','./assets/exercises/chest_press.svg','./assets/exercises/seated_row.svg','./assets/exercises/lat_pulldown.svg','./assets/exercises/leg_press.svg','./assets/exercises/leg_curl.svg','./assets/exercises/leg_extension.svg','./assets/exercises/face_pull.svg','./assets/exercises/shoulder_press.svg','./assets/exercises/farmer_carry.svg','./assets/exercises/step_up.svg','./assets/exercises/calf_raise.svg','./assets/exercises/pallof.svg','./assets/exercises/side_plank.svg','./assets/exercises/dead_bug.svg','./assets/exercises/bird_dog.svg','./assets/exercises/walk.svg','./assets/exercises/chair_stand.svg','./assets/exercises/wall_sit.svg','./assets/exercises/balance.svg','./assets/exercises/march.svg','./assets/enemies/giant-rat.svg','./assets/enemies/goblin-minion.svg','./assets/enemies/wolf.svg','./assets/enemies/skeleton.svg','./assets/enemies/goblin-warrior.svg','./assets/enemies/dire-wolf.svg','./assets/enemies/goblin-boss.svg','./assets/enemies/minotaur-skeleton.svg','./assets/enemies/ogre.svg','./assets/enemies/giant-scorpion.svg','./assets/enemies/red-dragon-wyrmling.svg','./assets/enemies/troll.svg','./assets/enemies/young-red-dragon.svg'];
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;if(event.request.mode==='navigate'){event.respondWith(fetch(event.request).then(response=>{const clone=response.clone();caches.open(CACHE).then(cache=>cache.put('./index.html',clone));return response;}).catch(()=>caches.match('./index.html').then(cached=>cached||caches.match(`./index.html${v}`))));return;}event.respondWith(caches.match(event.request).then(cached=>cached||fetch(event.request).then(response=>{const clone=response.clone();caches.open(CACHE).then(cache=>cache.put(event.request,clone));return response;})));});
